version: "3.9"

services:
  snep:
    image: openstec/snep-pbx
    deploy:
      replicas: 1
    ports:
      - "81:80"
    depends_on:
      - mysql-snep
    networks:
      - rede-snep
    volumes:
      - data:/var/www/html
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini # Precisa criar o arquivo custom.ini
    environment:
      - VIRTUAL_HOST=snep.belaevaidosa.com.br
      - LETSENCRYPT_HOST=snep.belaevaidosa.com.br
      - LETSENCRYPT_EMAIL=seuemail@dominio.com # Substitua pelo seu e-mail

  mysql-snep:
    image: mysql:5.7
    deploy:
      replicas: 1
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=snep
      - MYSQL_USER=snep
      - MYSQL_PASSWORD=sneppass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - rede-snep
    restart: always

  phpmyadmin:
    image: phpmyadmin
    deploy:
      replicas: 1
      restart_policy:
        condition: always
    environment:
      - PMA_HOST=mysql-snep
    ports:
      - "8090:80"
    depends_on:
      - mysql-snep
    networks:
      - rede-snep

networks:
  rede-snep:

volumes:
  db_data:
  data:
